### ISSUE TITLE
Error while repairing – invalid RunState and timestamps

### ISSUE THREAD

**Issue by ynsdl** [thelastpickle/cassandra-reaper#603]
Hi,

I have a cassandra cluster setup with 3 nodes. On each node JMX authentication is enabled

When ı start to repair, ı see some errors on cassandra-reaper.log

What does it means ?

ERROR  [2019-01-17 07:20:54,850] [ReaperApplication-scheduler] i.c.ReaperApplication - Failed purging repair runs from history 
java.lang.NullPointerException: null
        at io.cassandrareaper.service.PurgeService.lambda$purgeRepairRunsByHistoryDepth$1(PurgeService.java:94)
        at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
        at java.util.TimSort.sort(TimSort.java:220)
        at java.util.Arrays.sort(Arrays.java:1512)
        at java.util.ArrayList.sort(ArrayList.java:1454)
        at io.cassandrareaper.service.PurgeService.purgeRepairRunsByHistoryDepth(PurgeService.java:93)
        at io.cassandrareaper.service.PurgeService.purgeDatabase(PurgeService.java:71)
        at io.cassandrareaper.ReaperApplication.lambda$schedulePurge$1(ReaperApplication.java:308)
        at com.codahale.metrics.InstrumentedScheduledExecutorService$InstrumentedRunnable.run(InstrumentedScheduledExecutorService.java:235)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by ynsdl** [comment]
Hi,

cassandra-reaper working in memory so ı have restarted cassandra-reaper and send a new repair request to cassandra. So ı cant see last repair history but ı can share new repair history.

storageType: memory

ID | f6ccc950-1a2c-11e9-80d0-87cb49720274
-- | --
Owner | Mustafa
Cause | msg log retention
Last event | Postponed due to affected hosts already doing repairs
Start time | January 17, 2019 10:53 AM
End time |  
Pause time |  
Duration | 8 minutes 35 seconds
Segment count | 73
Segment repaired | 0
Intensity | 0.8999999761581421
Repair parallelism | PARALLEL
Incremental repair | false
Repair threads | 4
Nodes |  
Datacenters |  
Blacklist |  
Creation time | January 17, 2019 10:53 AM

**Comment by michaelsembwever** [comment]
Is this a problem @ynsdl ?

**Comment by SesquipedalianDefenestrator** [comment]
I'm running 1.4.1 currently and have the same issue. This is definitely a problem, because it prevents purging older repair entries automatically, and the repair database will grow without bounds. 

If I abort a repair, it always has an endTime of NULL.  Any entries with an endTime of NULL cause the error and a failure to purge old entries.

I'm using the h2 database.  Clearing out aborted entries via the UI works if they're recent, but some of mine were too old to show up in "last 100" and i had to use the h2 shell to clean the entries up (which fixed the immediate production issue)

**Comment by SesquipedalianDefenestrator** [comment]
Looks like RepairManager. abortRepairRun() sets pauseTime(DateTime.now()), but doesn't touch endTime.  Seems like setting endTime to DateTime.now() on abort would fix this specific issue, but I'm guessing it would violate assumptions elsewhere:
https://github.com/thelastpickle/cassandra-reaper/blob/d47930a9fe99e19adbe84b78cea7465822d8d471/src/server/src/main/java/io/cassandrareaper/storage/cassandra/Migration009.java#L71

Maybe compare against pauseTime instead in the specific case where it's ABORTED?

**Comment by michaelsembwever** [comment]
@SesquipedalianDefenestrator 
> I'm using the h2 database. Clearing out aborted entries via the UI works if they're recent, but some of mine were too old to show up in "last 100" and i had to use the h2 shell to clean the entries up (which fixed the immediate production issue)

would you mind sharing the h2 shell command to help others that need to workaround the problem (in the meantime) as well?

**Comment by SesquipedalianDefenestrator** [comment]
Sure thing:
1.  Get the h2lib jar from somewhere.  Debian has it in the repo (libh2-java)
2.  Stop Reaper to avoid conflicts/corruption accessing the DB.
3.  Open the H2 tool: `sudo -u reaper java -cp /usr/share/java/h2.jar org.h2.tools.Shell -url 'jdbc:h2:/var/lib/cassreaper/db;MODE=PostgreSQL'` (with whatever database URL is in the 'url:' parameter in your config).
4.  Since there's a foreign key set up, first delete the segments associated with the aborted runs:  `DELETE FROM REPAIR_SEGMENT WHERE RUN_ID IN (SELECT ID from REPAIR_RUN WHERE STATE='ABORTED');`
5.  Then delete the aborted runs themselves: `DELETE from REPAIR_RUN WHERE STATE='ABORTED';`
6.  Start Reaper back up

**Comment by michaelsembwever** [comment]
> Looks like RepairManager. abortRepairRun() sets pauseTime(DateTime.now()), but doesn't touch endTime. Seems like setting endTime to DateTime.now() on abort would fix this specific issue, but I'm guessing it would violate assumptions elsewhere: `cassandra-reaper/src/server/src/main/java/io/cassandrareaper/storage/cassandra/Migration009.java`

Note, `RepairRun.RunState` is not the same as `RepairSegment.State`.

> If I abort a repair, it always has an endTime of NULL. Any entries with an endTime of NULL cause the error and a failure to purge old entries.

Indeed there is a problem with incorrect combinations of `RepairRun.RunState`, `startTime`, `pauseTime`, and `endTime`.

I've created https://github.com/thelastpickle/cassandra-reaper/pull/651 which
 - ensures correct state and timestamp combinations during runtime (`RepairRun`, `RepairManager`, `MemoryStorage`, and `PostgresStorage`), 
 - adds preconditions to catch this error in the future, and
 - adds a migration script to fix existing installations.

I do need some help reviewing and validating this, being short of time atm. @SesquipedalianDefenestrator  are you able to help me out?

**Comment by SesquipedalianDefenestrator** [comment]
Happy to take a quick look, but my Java skills are probably best described as "read-only/triage"

**Comment by rsaffi** [comment]
My scenario is: I was running 1.4.0, paused an ongoing repair ("Stop", but no "Abort"), shutdown the service, upgraded to 1.4.2 and now service won't come up due to the error below:

```May  7 11:26:23 rpr01 cassandra-reaper[32002]: Looking for reaper in /usr/share/cassandra-reaper/
May  7 11:26:28 rpr01 cassandra-reaper[32002]: io.cassandrareaper.ReaperException: java.lang.IllegalStateException: endTime only valid when runState is terminated. PAUSED 2019-05-07T08:36:33.532Z
May  7 11:26:28 rpr01 cassandra-reaper[32002]: #011at io.cassandrareaper.service.RepairManager.resumeRunningRepairRuns(RepairManager.java:112)
May  7 11:26:28 rpr01 cassandra-reaper[32002]: #011at io.cassandrareaper.ReaperApplication.run(ReaperApplication.java:280)
May  7 11:26:28 rpr01 cassandra-reaper[32002]: #011at io.cassandrareaper.ReaperApplication.run(ReaperApplication.java:81)
May  7 11:26:28 rpr01 cassandra-reaper[32002]: #011at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43)
May  7 11:26:28 rpr01 cassandra-reaper[32002]: #011at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
May  7 11:26:28 rpr01 cassandra-reaper[32002]: #011at io.dropwizard.cli.Cli.run(Cli.java:78)
May  7 11:26:28 rpr01 cassandra-reaper[32002]: #011at io.dropwizard.Application.run(Application.java:93)
May  7 11:26:28 rpr01 cassandra-reaper[32002]: #011at io.cassandrareaper.ReaperApplication.main(ReaperApplication.java:100)
May  7 11:26:28 rpr01 cassandra-reaper[32002]: Caused by: java.lang.IllegalStateException: endTime only valid when runState is terminated. PAUSED 2019-05-07T08:36:33.532Z
May  7 11:26:28 rpr01 cassandra-reaper[32002]: #011at com.google.common.base.Preconditions.checkState(Preconditions.java:721)
May  7 11:26:28 rpr01 cassandra-reaper[32002]: #011at io.cassandrareaper.core.RepairRun$Builder.build(RepairRun.java:303)
May  7 11:26:28 rpr01 cassandra-reaper[32002]: #011at io.cassandrareaper.storage.postgresql.RepairRunMapper.map(RepairRunMapper.java:60)
May  7 11:26:28 rpr01 cassandra-reaper[32002]: #011at io.cassandrareaper.storage.postgresql.RepairRunMapper.map(RepairRunMapper.java:31)
May  7 11:26:28 rpr01 cassandra-reaper[32002]: #011at org.skife.jdbi.v2.Query$4.munge(Query.java:183)
May  7 11:26:28 rpr01 cassandra-reaper[32002]: #011at org.skife.jdbi.v2.QueryResultSetMunger.munge(QueryResultSetMunger.java:41)
May  7 11:26:28 rpr01 cassandra-reaper[32002]: #011at org.skife.jdbi.v2.SQLStatement.internalExecute(SQLStatement.java:1344)
May  7 11:26:28 rpr01 cassandra-reaper[32002]: #011at org.skife.jdbi.v2.Query.fold(Query.java:173)
May  7 11:26:28 rpr01 cassandra-reaper[32002]: #011at org.skife.jdbi.v2.Query.list(Query.java:82)
May  7 11:26:28 rpr01 cassandra-reaper[32002]: #011at org.skife.jdbi.v2.sqlobject.ResultReturnThing$IterableReturningThing.result(ResultReturnThing.java:253)
May  7 11:26:28 rpr01 cassandra-reaper[32002]: #011at org.skife.jdbi.v2.sqlobject.ResultReturnThing.map(ResultReturnThing.java:43)
May  7 11:26:28 rpr01 cassandra-reaper[32002]: #011at org.skife.jdbi.v2.sqlobject.QueryHandler.invoke(QueryHandler.java:41)
May  7 11:26:28 rpr01 cassandra-reaper[32002]: #011at org.skife.jdbi.v2.sqlobject.SqlObject.invoke(SqlObject.java:224)
May  7 11:26:28 rpr01 cassandra-reaper[32002]: #011at org.skife.jdbi.v2.sqlobject.SqlObject$3.intercept(SqlObject.java:133)
May  7 11:26:28 rpr01 cassandra-reaper[32002]: #011at org.skife.jdbi.v2.sqlobject.CloseInternalDoNotUseThisClass$$EnhancerByCGLIB$$849b0315.getRepairRunsWithState(<generated>)
May  7 11:26:28 rpr01 cassandra-reaper[32002]: #011at io.cassandrareaper.storage.PostgresStorage.getRepairRunsWithState(PostgresStorage.java:211)
May  7 11:26:28 rpr01 cassandra-reaper[32002]: #011at io.cassandrareaper.service.RepairManager.resumeRunningRepairRuns(RepairManager.java:106)
May  7 11:26:28 rpr01 cassandra-reaper[32002]: #011... 7 more
May  7 11:26:28 rpr01 systemd[1]: cassandra-reaper.service: Main process exited, code=exited, status=1/FAILURE
May  7 11:26:28 rpr01 systemd[1]: cassandra-reaper.service: Unit entered failed state.
May  7 11:26:28 rpr01 systemd[1]: cassandra-reaper.service: Failed with result 'exit-code'.```

**Comment by michaelsembwever** [comment]
@rsaffi , during the upgrade to `1.4.2` that repair segment data should have been corrected.
Looking at https://github.com/thelastpickle/cassandra-reaper/blob/master/src/server/src/main/resources/db/postgres/V12_0_0__fix_repair_run_timestamps.sql#L32 I see there's a bug there in which run states are considered `terminated`.

I've put a PR in for the fix at https://github.com/thelastpickle/cassandra-reaper/pull/656

In the meantime you can fix this by running the following sql manually:
```
UPDATE repair_run
SET end_time = CAST(NULL as TIMESTAMP WITH TIME ZONE)
WHERE end_time IS NOT NULL
AND state NOT IN ('ERROR', 'DONE', 'ABORTED', 'DELETED');

UPDATE repair_run
SET end_time = start_time
WHERE end_time IS NULL
AND state IN ('ERROR', 'DONE', 'ABORTED', 'DELETED');
```

**Comment by rsaffi** [comment]
> @rsaffi , during the upgrade to `1.4.2` that repair segment data should have been corrected.
> ```
> UPDATE repair_run
> SET end_time = CAST(NULL as TIMESTAMP WITH TIME ZONE)
> WHERE end_time IS NOT NULL
> AND state NOT IN ('ERROR', 'DONE', 'ABORTED', 'DELETED');
> 
> UPDATE repair_run
> SET end_time = start_time
> WHERE end_time IS NULL
> AND state IN ('ERROR', 'DONE', 'ABORTED', 'DELETED');
> ```
Did that but oddly the service only started after my third attempt. Couldn't really understand why, but it is up and running now. Something else that is odd is that when I'm on the "Repairs" tab the "Running" table keeps loading forever. I can still see ongoing repairs through the "Clusters" tab, though.

**Comment by rsaffi** [comment]
And now the service simply crashed and this is what I found on the logs:
```ERROR  [2019-05-08 09:46:08,534] [SchedulingManagerTimer] i.c.s.SchedulingManager - failed managing schedule for run with id: 00000000-0000-0214-0000-000000000000 
ERROR  [2019-05-08 09:46:08,534] [SchedulingManagerTimer] i.c.s.SchedulingManager - catch exception 
java.lang.IllegalStateException: pausedTime only valid when runState is PAUSED. ABORTED 2019-03-12T12:56:52.349Z
        at com.google.common.base.Preconditions.checkState(Preconditions.java:721)
        at io.cassandrareaper.core.RepairRun$Builder.build(RepairRun.java:295)
        at io.cassandrareaper.storage.postgresql.RepairRunMapper.map(RepairRunMapper.java:60)
        at io.cassandrareaper.storage.postgresql.RepairRunMapper.map(RepairRunMapper.java:31)
        at org.skife.jdbi.v2.Query$4.munge(Query.java:183)
        at org.skife.jdbi.v2.QueryResultSetMunger.munge(QueryResultSetMunger.java:41)
        at org.skife.jdbi.v2.SQLStatement.internalExecute(SQLStatement.java:1344)
        at org.skife.jdbi.v2.Query.fold(Query.java:173)
        at org.skife.jdbi.v2.Query.list(Query.java:82)
        at org.skife.jdbi.v2.sqlobject.ResultReturnThing$IterableReturningThing.result(ResultReturnThing.java:253)
        at org.skife.jdbi.v2.sqlobject.ResultReturnThing.map(ResultReturnThing.java:43)
        at org.skife.jdbi.v2.sqlobject.QueryHandler.invoke(QueryHandler.java:41)
        at org.skife.jdbi.v2.sqlobject.SqlObject.invoke(SqlObject.java:224)
        at org.skife.jdbi.v2.sqlobject.SqlObject$3.intercept(SqlObject.java:133)
        at org.skife.jdbi.v2.sqlobject.CloseInternalDoNotUseThisClass$$EnhancerByCGLIB$$b02f7e81.getRepairRunsForUnit(<generated>)
        at io.cassandrareaper.storage.PostgresStorage.getRepairRunsForUnit(PostgresStorage.java:202)
        at io.cassandrareaper.service.SchedulingManager.repairRunAlreadyScheduled(SchedulingManager.java:264)
        at io.cassandrareaper.service.SchedulingManager.manageSchedule(SchedulingManager.java:145)
        at io.cassandrareaper.service.SchedulingManager.run(SchedulingManager.java:100)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
ERROR  [2019-05-08 09:46:08,534] [SchedulingManagerTimer] i.c.s.SchedulingManager - SchedulingManager failed. Exiting JVM. 
DEBUG  [2019-05-08 09:46:08,538] [Thread-14] o.e.j.u.t.ShutdownThread -  
java.lang.IllegalStateException: !STOPPED
        at org.eclipse.jetty.server.handler.HandlerWrapper.destroy(HandlerWrapper.java:147)
        at org.eclipse.jetty.util.thread.ShutdownThread.run(ShutdownThread.java:144)

**Comment by michaelsembwever** [comment]
those paused repair segments also need their pauseTimes removed.
please run
```
UPDATE repair_run
SET pause_time = CAST(NULL as TIMESTAMP WITH TIME ZONE)
WHERE pause_time IS NOT NULL
AND state <> 'PAUSED';
```

**Comment by michaelsembwever** [comment]
For the Cassandra backend this wasn't properly fixed until #665
